In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Combined_dataset.csv")
df.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [3]:
# explore data
print("Shape of the data:", df.shape)
print('====================================================================================================================')
print("Columns in the data:", df.columns)
print('====================================================================================================================')
print("Data types of each column:\n", df.dtypes)
print('====================================================================================================================')
print("Number of missing values in each column:\n", df.isnull().sum())

Shape of the data: (1000, 24)
====================================================================================================================
Columns in the data: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
====================================================================================================================
Data types of each column:
 product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object
====================================================================================================================
Number of missing values in each column:
 product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [ ]:
# Handling NaN values

df1 = df.copy()

df1["what_customers_said"] = df1["what_customers_said"].fillna("No comments")
df1["seller_name"] = df1["seller_name"].fillna("Unknown")
df1["seller_information"] = df1["seller_information"].fillna("Unknown")
df1["discount"] = df1["discount"].fillna(0)
df1["videos"] = df1["videos"].fillna("No Video")
df1["variations"] = df1["variations"].fillna("No Variants")
#using another field to know if there are any variations or not, as it would be easier to filter the products with variations if needed!
df1["has_variations"] = df1["variations"].notna()

df1.head(3)

#There are no columns in the dataset that can be wither filled with any statistic or any fillna technique, they're all categorical and textual
#so it's better to fill them with a placeholder value that indicates the absence of the data.

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,has_variations
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,No comments,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,No comments,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,No comments,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True

In [5]:
# basic operations: filter rows and select columns
selected_columns = df1[["product_id", "title", "category", "rating", "initial_price", "discount"]]
high_rated = selected_columns[(df1["rating"] > 4) & (df1["ratings_count"] > 70)]
high_rated.head(3)

    product_id   title   category  rating  initial_price  discount
2     17633752   Lavie  backpacks     4.4           2999      65.0
3      1376949  F Gear  backpacks     4.4           1675      52.0
24    15115018  Jockey        bra     4.4            579       0.0

In [6]:
# drop duplicates
df1 = df1.drop_duplicates(subset=["product_id"])
df1.shape

(1000, 25)

In [7]:
# Derived column
df1["calculated_final_price"] = df1["initial_price"] - (df1["initial_price"] * df1["discount"] / 100)
df1["calculated_final_price"] = df1["calculated_final_price"]

df1.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,has_variations,calculated_final_price
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1677.90
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1884.35
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1049.65

In [8]:
# save cleaned combined dataset
df1.to_csv("cleaned_Combined_dataset.csv", index=False)
df1.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,has_variations,calculated_final_price
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1677.90
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1884.35
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,True,1049.65