In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sports-shoes.csv")
df.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,NaN,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":22,""2_stars"":10,""3_stars"":13,""4_star...",NaN,Tru███m R███il,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",NaN,CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",NaN,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes

In [3]:
#explore data
print("Shape of the data:", df.shape)
print('====================================================================================================================')
print("Columns in the data:", df.columns)
print('====================================================================================================================')
print("Data types of each column:\n", df.dtypes)
print('====================================================================================================================')
print("Number of missing values in each column:\n", df.isnull().sum())

Shape of the data: (51, 24)
====================================================================================================================
Columns in the data: Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
====================================================================================================================
Data types of each column:
 product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said       float64
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object
====================================================================================================================
Number of missing values in each column:
 product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                  23
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       51
seller_name               14
sizes                      0
videos                    21
seller_information        14
variations                32
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [4]:
#Handling Nan values
df1 = df.drop(columns=["what_customers_said"])
df1["seller_name"] = df1["seller_name"].fillna(value="Unknown")
df1["seller_information"] = df1["seller_information"].fillna(value="Unknown")
df1["discount"] = df1["discount"].fillna(value=0)
df1["videos"] = df1["videos"].fillna(value="https://youtu.be/dQw4w9WgXcQ?t=0")
df1["variations"] = df1["variations"].fillna(value="No Variants")
df1.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",https://youtu.be/dQw4w9WgXcQ?t=0,Unknown,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,0.0,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":22,""2_stars"":10,""3_stars"":13,""4_star...",Tru███m R███il,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,No Variants,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,"""₹751.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",https://youtu.be/dQw4w9WgXcQ?t=0,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes

In [5]:
#basic operations (filter rows, select columns)
df1[df1["rating"] > 3].head(3)
df1[(df1["rating"] > 4) & (df1["ratings_count"] > 70)][["product_id", "title"]].head(3)

   product_id   title
2    13686682  Campus
5    20071104  ADIDAS
8    20071558  ADIDAS

In [6]:
#drop duplicates
df1 = df1.drop_duplicates(subset=["product_id"])
df1.shape

(51, 23)

In [7]:
#Derived column 
df1["final_price"] = df1["initial_price"] - (df1["initial_price"] * df1["discount"] / 100)
df1.head(3)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17745816,Lancer,Men Navy Blue Textile Running Non-Marking Shoes,4.0,6,1999.0,40.0,1199.40,INR,http://assets.myntassets.com/assets/images/177...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""6"",""value"":""26.4cm"",""value_name"":""To...",https://youtu.be/dQw4w9WgXcQ?t=0,Unknown,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
1,17631178,Slazenger,Men White Woven Design Walking Shoes,3.7,127,3599.0,0.0,3599.00,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":22,""2_stars"":10,""3_stars"":13,""4_star...",Tru███m R███il,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","[""rw-17631178_cae700""]",Sho███o. ███-10█████████enu███████████████████...,No Variants,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes
2,13686682,Campus,Women White Mesh Walking Shoes,4.1,452,799.0,6.0,751.06,INR,http://assets.myntassets.com/assets/images/136...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":31,""2_stars"":18,""3_stars"":56,""4_star...",CAM███ AC███EWE█████████D,"[{""size"":""4"",""value"":""24.8cm"",""value_name"":""To...",https://youtu.be/dQw4w9WgXcQ?t=0,Kha███ No███/25█████████ark███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on Citi C...",sports-shoes

In [10]:
df = df1
df
df.to_csv("cleaned_sports-shoes.csv", index=False)